In [ ]:
import sys
import numpy as np

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([1.2,.7,3,5])
b[0],b[1]

(1.2, 0.7)

## **array accessing**

In [ ]:
a[0],a[1]

(1, 2)

## * **slicing of an array**


In [ ]:
a[0:]

array([1, 2, 3, 4, 5])

In [ ]:
a[0:3]

array([1, 2, 3])

In [ ]:
#negative slicing
a[0:-1]

array([1, 2, 3, 4])

# **d.type** gives the datatype

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b.dtype

dtype('float64')

In [ ]:
np.array([1,2,3,4],dtype=float)

array([1., 2., 3., 4.])

In [ ]:
a=np.array([1,2,3,4,5])

##  To convert array from int to float

In [ ]:
np.array([1,2,3,4],dtype=np.float64)

array([1., 2., 3., 4.])

In [ ]:
np.array([1,2,3,4],dtype=np.str_)

array(['1', '2', '3', '4'], dtype='<U1')

**matrix representation of array**

In [ ]:
A=np.array([
    [1,2,3],
    [4,5,6]
])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6]])

** A.shape** gives (no. of rows,no of colm)

---


** A.size** gives (no of elements of matrix)

---


** A.ndim** gives (no of dimension of matrix)

In [ ]:
A.shape

(2, 3)

In [ ]:
A.ndim

2

In [ ]:
A.size

6

In [ ]:
A.sum()#gives sum of elements of an matrix

21

In [ ]:
A.mean()#gives mean of all the elements of matrix

3.5

In [ ]:
A.std()#gives standard deviation of elements of matrix

1.707825127659933

In [ ]:
A.var()#gives variance of a matrix

2.9166666666666665

In [ ]:
A.sum(axis=0)

array([5, 7, 9])

In [ ]:
A.sum(axis=1)

array([ 6, 15])

In [ ]:
a = np.arrange(100)

**BROADCASTING AND VECTORISED OPERATIONS**

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
a+10

array([11, 12, 13, 14, 15])

In [ ]:
a*10

array([10, 20, 30, 40, 50])

In [ ]:
a

array([1, 2, 3, 4])

**NUMPY is Immutable**


In [ ]:
b    #array is from top an example

array([1.2, 0.7, 3. , 5. ])

In [ ]:
b=np.array([1.2,0.7,3.0,5.0],dtype=np.int64)

In [ ]:
b

array([1, 0, 3, 5])

In [ ]:
a+b

array([2, 2, 6, 9])

In [ ]:
b=np.array([1,0,3,5])

In [ ]:
b

array([1, 0, 3, 5])

In [ ]:
[i*100 for i in b]

[100, 0, 300, 500]

**BOOLEAN ARRAYS**

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a[[True,False,False,True]]

array([1, 4])

In [ ]:
a>=2

array([False,  True,  True,  True])

In [ ]:
a.mean()

2.5

In [ ]:
a[a>a.mean()]

array([3, 4])

In [ ]:
a.var()

1.25

In [ ]:
a[a>a.var()]

array([2, 3, 4])

In [ ]:
a=np.array([1,2,3,4],dtype=np.float64)

In [ ]:
a

array([1., 2., 3., 4.])

In [1]:
import pandas as pd
import numpy as np

In [2]:
atte_per=pd.Series([59,90,65.5,71.4,80,100,82.6])

In [3]:
atte_per

0     59.0
1     90.0
2     65.5
3     71.4
4     80.0
5    100.0
6     82.6
dtype: float64

In [4]:
atte_per.name='attendance percentage'

In [5]:
atte_per

0     59.0
1     90.0
2     65.5
3     71.4
4     80.0
5    100.0
6     82.6
Name: attendance percentage, dtype: float64

In [6]:
atte_per.values

array([ 59. ,  90. ,  65.5,  71.4,  80. , 100. ,  82.6])

In [7]:
type(atte_per.values)

numpy.ndarray

In [8]:
atte_per[atte_per<75]

0    59.0
2    65.5
3    71.4
Name: attendance percentage, dtype: float64

In [9]:
atte_per.index

RangeIndex(start=0, stop=7, step=1)

In [10]:
atte_per.index=['rahul',
                'revanth reddy',
                'ktr',
                'kcr',
                'musk',
                'jack',
                'ram']

In [11]:
atte_per

rahul             59.0
revanth reddy     90.0
ktr               65.5
kcr               71.4
musk              80.0
jack             100.0
ram               82.6
Name: attendance percentage, dtype: float64

In [12]:
atte_per.iloc[1]

90.0

In [13]:
#similarly
atte_per['kcr']

71.4

In [14]:
atte_per

rahul             59.0
revanth reddy     90.0
ktr               65.5
kcr               71.4
musk              80.0
jack             100.0
ram               82.6
Name: attendance percentage, dtype: float64

In [17]:
atte_per.mean( )

78.35714285714286

In [19]:
atte_per.median()

80.0

In [20]:
atte_per.std()

14.218984626530961

In [21]:
atte_per.var()

202.17952380952383

In [24]:
atte_per['ktr']

65.5

In [26]:
atte_per>75

rahul            False
revanth reddy     True
ktr              False
kcr              False
musk              True
jack              True
ram               True
Name: attendance percentage, dtype: bool

In [28]:
np.log(atte_per)

rahul            4.077537
revanth reddy    4.499810
ktr              4.182050
kcr              4.268298
musk             4.382027
jack             4.605170
ram              4.414010
Name: attendance percentage, dtype: float64

**data modifying**

In [29]:
atte_per['ktr']=100               # modification is performed

In [30]:
atte_per

rahul             59.0
revanth reddy     90.0
ktr              100.0
kcr               71.4
musk              80.0
jack             100.0
ram               82.6
Name: attendance percentage, dtype: float64

In [31]:
atte_per[atte_per<75]=75

In [33]:
atte_per

rahul             75.0
revanth reddy     90.0
ktr              100.0
kcr               75.0
musk              80.0
jack             100.0
ram               82.6
Name: attendance percentage, dtype: float64